### ISSUE TITLE
FileNotFoundError while upgrading stock_request

### ISSUE THREAD

**Issue by jerzyk** [OCA/stock-logistics-warehouse#1643]
## Module
stock_request

## Describe the bug

FileNotFoundError: File not found: stock_request/migrations/14.0.1.3.0/noupdate_changes.xml

## To Reproduce
**Affected versions**: 
15.0.1.4.0

1. do upgrade from cmd line: odoo-bin -u stock_request

**Additional context**

stock_request/migrations/15.0.1.4.0/post-migration.py

path is: migrations/14.0.1.3.0/noupdate_changes.xml should be migrations/15.0.1.4.0/noupdate_changes.xml ?

additionally openupgradelib is used, but not specified in external dependences

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/stock-logistics-warehouse/commit/1d2ae81c6c8c86fdf4f4c7354d83a6368e390d48. Thanks for notifying. `openupgradelib` shouldn't be on external dependencies, because it's not needed if you install module from scratch. Install the library everywhere in any case, as it's a must in OCA.
