### ISSUE TITLE
Use of module stock_mts_mto_rule in manufacturing orders

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-warehouse#185]
We'd like to explore the possibility of using the module "stock_mts_mto_rule" in the context of manufacturing orders. 

That is, when a manufacturing order is confirmed, and the stock moves are created, the application should reserve whatever stock is available, following a mts rule, and if there's none left, should evaluate a mto rule.

Any thoughts on how to set it up?

cc @florian-dacosta

**Comment by pedrobaeza** [comment]
@jbeficent, did you try something?

**Comment by sdalexander** [comment]
Hi @jbeficent 

we would like to do something similar, did you manage to configure a route to do this?

regards
Steve

**Comment by florian-dacosta** [comment]
@jbeficent Sorry to answer so late...

The module was originally made for buying purpose.
I think it can also be used to create or not a manufacturing order depending on the stock of the end product.

But once the manufacturing order is created, the mts+mto rule won't be able to help anymore.
I just had a quick look into the mrp module, and I think you can't make your usecase work with this module.

I guess you would have to override the _get_raw_material_procure_method method on mrp.production model to be able to achieve what you want....

**Comment by michaeljohn32** [comment]
At one point, I did work on this for v.8.  I extended the action_confirm() method.  I haven't worked on it since, but the code is AGPL and located here: https://github.com/michaeljohn32/odooaddons as mrp_mto_with_stock

**Comment by sdalexander** [comment]
Hi Florianregarding the stock_mts_mto_rule, will the module work with an order for a product with a BOM type of SET ?see my issue from yesterdayhttps://github.com/OCA/stock-logistics-warehouse/issues/218regardsSteveOn 09 November 2016 at 13:23 Florian notifications@github.com wrote:@jbeficent Sorry to answer so late...The module was originally made for buying purpose. I think it can also be used to create or not a manufacturing order depending on the stock of the end product.But once the manufacturing order is created, the mts+mto rule won't be able to help anymore. I just had a quick look into the mrp module, and I think you can't make your usecase work with this module.I guess you would have to override the _get_raw_material_procure_method method on mrp.production model to be able to achieve what you want....—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by JordiBForgeFlow** [comment]
We have resolved this issue here: https://github.com/OCA/manufacture/pull/191. Can you review, so that we can merge it as soon as possible?

**Comment by rousseldenis** [comment]
https://github.com/OCA/manufacture/pull/191 merged
