### ISSUE TITLE
[11.0] stock_mts_mto_rule: MTO is not working 

### ISSUE THREAD

**Issue by Frenky007** [OCA/stock-logistics-warehouse#505]
MTS is working very fine but since I have product with 0 amount in the stock no Purchase order is done. 
I can avoided with reordering rules but in this case I am loosing the main source document in the PO and is mentioned there OP means reordering number of the product. 
any ideas?

**Comment by pedrobaeza** [comment]
Is this something about a module in this repository?

**Comment by umiphos** [comment]
@Frenky007 the module has a bug because it does not have in consideration the buy process for some materials, but for direct Sale Order or Manufacture Order for an item with MTS+MTO, it works fine for the listed items, but, if you do:

- Product with materials that have MTS+MTO

Let's say that you want the materials to be picked from stock, then it will not work. It has a deep problem within odoo and the decision taking. We were working to solve it in 
https://github.com/OCA/stock-logistics-warehouse/pull/500 but that make MTO(always buys because it founds the route for MTS+MTO), so, we are still working so MTS+MTO plays good with odoo....

cc @moylop260 @rsilvam21

**Comment by Frenky007** [comment]
@umiphos Okay... please let me us know if there will be some new step forward Once again thanks for information!

**Comment by umiphos** [comment]
@Frenky007 until we get a new idea, we are leaving this fix to that oca module as it is(un merged), our fix  proposes that the MRP decision taking MTS or MTO, takes in count the routes that the MTS+MTO module adds, you can always try that on your own module(like we've done) until this fix is merged.

NOTE: If you apply that patch in your module, the MTS+MTO module will act for materials in MRP as MTO(always buys the whole pack).

**Comment by Frenky007** [comment]
@umiphos thank you very much! after using the MRP MTO with Stock module it is working exactly as we wish! I am very appreciate your support

**Comment by umiphos** [comment]
@Frenky007 glad to help
@pedrobaeza this is a real bug in the **stock_mts_mto_rule** module, don't close this issue until we/someone fix it, please

**Comment by moylop260** [comment]
What about creates a PR to odoo to fix support multi-rules?

**Comment by sergiocorato** [comment]
related #572
