### ISSUE TITLE
[RFC] Product packaging: Split modules and migrate to good repo

### ISSUE THREAD

**Issue by rousseldenis** [OCA/stock-logistics-warehouse#604]
The packaging uom management and dependent modules are split into :

* [x] packaging_uom : https://github.com/OCA/product-attribute/pull/486
* [ ] sale_packaging : https://github.com/OCA/sale-workflow/pull/858
* [x] stock_packaging (New) : https://github.com/OCA/stock-logistics-warehouse/pull/603
* [ ] purchase_packaging: https://github.com/OCA/purchase-workflow/pull/687
* [ ] purchase_stock_packaging (New): https://github.com/OCA/purchase-workflow/pull/689

Reviews are welcome !

**Comment by pedrobaeza** [comment]
Do you want a new repo?

**Comment by rousseldenis** [comment]
No, I'm using existing ones.

I've done this to warn users on what I'm doing.

**Comment by andres-pcg** [comment]
I have migrated the sale_packaging one, maybe you would like to take a look of it. I’ve been trying to do same with packaging_oum but the packaging view on the product.template model has been giving me a hard time 😅

**Comment by rousseldenis** [comment]
@andrp92 I've done technical migration. I haven't done functional tests yet. I'll do it asap.

**Comment by andres-pcg** [comment]
@rousseldenis i've tested it and found out that the packaging_uom's view is not working properly. On the product.template model, Odoo has added groups on the packaging view, therefore the v11 view does not longer work nor the context that we are passing to it. I resolved the visual part of it by adding an xpath to the view **product_packaging_view_form_inherit_packaging_uom**, 

`<xpath expr="//group[@name='qty']" position="after">
     <group>
         <field name="uom_categ_domain_id" invisible="1"/>
         <field name="uom_id" domain="[('category_id', '=', uom_categ_domain_id)]" required="True"/>
     </group>
   </xpath>`

But this did not resolve the functional part of it. The **uom_id** field comes empty instead of showing the unit of measures related to the product uom category.


Should i add this coment to the PR? Hope this helps

**Comment by rousseldenis** [comment]
> Should i add this coment to the PR? Hope this helps

Yes, please

**Comment by rousseldenis** [comment]
@andrp92 I've just modified views and it seems more correct. Can you test ?

**Comment by andres-pcg** [comment]
@rousseldenis hey, thanks for your quick response. I tested it but still acting up. I blame odoo huge changes for that 😅. Will try to find out what are we missing. But uom_id field is still coming up empty

**Comment by rafaelbn** [comment]
Thanks you @rousseldenis for this work and resume
