### ISSUE TITLE
stock_available_immediately vs stock_available_unreserved

### ISSUE THREAD

**Issue by samy-m-dev** [OCA/stock-logistics-warehouse#669]
Hello,

Odoo 10.0

What is the exact difference between **stock_available_immediately** and **stock_available_unreserved**?

I cannot find any use case where these values will be different?

Thank you!

**Comment by florian-dacosta** [comment]
Hi,
The difference is that stock_available_unreserved take the stock reservation into account while stock_available_immediatly take the outgoing stock.
So you could have different value in case you do not reserve all your stock, even though you could.

One use case : 
A firm that deliver its sale orders at different date depending on the customer request.
So, there is sale order planned in 2 days, others in 2 months and others in 6 months
Maybe we do not want to reserve stock for an order planned in 6 months, because it would block the stock and then block more urgent orders.
In this case, you could have unreserved stock, which is not really "available immediately".

Let's say, you have 2 stock.
2 sale order of 1 product, one planned tomorrow, and the other in a month.
You decide you want to start reserving products only 15 days before planned date.
So only 1 product is reserved, while you actually have 2 outgoing products.
=> stock_available_unreserved qty = 1
=> stock_available_immediately = 0

Well, there are probably use cases more consistent, this is just a quick example !

**Comment by samy-m-dev** [comment]
@florian-dacosta Thanks a lot very clear explanation 👍
